### PR TITLE
Black patch

### PR DESCRIPTION
**Pull request by speedbunny**
Night mode patch for autistic community and other people with sensory-overload issues.
Flag_standard_2048x1440
Flag_tablet_2048x2048
Flag_wide_2560x1440
Flag_preview_960x540
Flag_mobile_1080x1920

### CODE REVIEW

**Comment by speedbunny** [comment]
@microsoft-github-policy-service agree [company="{none}"]

**Comment by speedbunny** [comment]
@microsoft-github-policy-service agree

**Comment by speedbunny** [comment]
superceded by new merge

**Comment by speedbunny** [comment]
not sure why this has been closed - if you look at the onion skin it actually works.

**Comment by ant-7802** [comment]
please open this back up

**Pull request closed without merging**
